<?php

namespace MeetUpBundle\Repository;

/**
 * CommentaireMeetUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireMeetUpRepository extends \Doctrine\ORM\EntityRepository
{
}
