<?php

namespace MeetUpBundle\Repository;

/**
 * MeetUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetUpRepository extends \Doctrine\ORM\EntityRepository
{
}
