<?php

namespace MeetUpBundle\Repository;

/**
 * Vote3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Vote3Repository extends \Doctrine\ORM\EntityRepository
{
}
