<?php

namespace MeetUpBundle\Repository;

/**
 * Vote2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Vote2Repository extends \Doctrine\ORM\EntityRepository
{
}
