<?php

namespace MeetUpBundle\Repository;

/**
 * Vote1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Vote1Repository extends \Doctrine\ORM\EntityRepository
{
}
