app_user:
    resource: "@AppUserBundle/Controller/"
    type:     annotation
    prefix:   /


app:
    resource: "@AppBundle/Controller/"
    type:     annotation

oc_platform:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app_user_bis:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    


show:
    pattern:  /profil/{username}
    defaults:   { _controller: AppUserBundle:Profile:show }
    requirements:
        _method: GET

profile:
    pattern: /profil
    defaults:   { _controller: AppUserBundle:Profile:profil }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

lesrencontres_all:
    resource: "@MeetUpBundle/Resources/config/routing.yml"

messagerie:
    resource: "@MessagerieBundle/Resources/config/routing.yml"
    prefix:   /

fos_message:
    resource: "@MessagerieBundle/Resources/config/routing.xml"
    prefix: /messagerie

