recherche_off: 
  path: /recherche_maman
  defaults: { _controller:AppBundle:SearchMaman:search} 

oc_platform_inscription2:
    path: /inscription2
    defaults: { _controller: AppBundle:Advert:inscription2 }
