meet_up_homepage:
    path:     /homepageMeetUp
    defaults: { _controller: MeetUpBundle:Default:index }

add_meet_up:
  path: /add_meet_up
  defaults: { _controller: MeetUpBundle:MeetUp:add}

meet_up_view:
  path: /meet_up/{id_meetup}
  defaults: { _controller: MeetUpBundle:MeetUp:show}
  requirements:
    id: \d+

delete_meet_up:
  path: /delete_meet_up/{id_meetup}
  defaults: { _controller: MeetUpBundle:MeetUp:delete}
  requirements:
    id: \d+    

edit_meet_up:
  path: /edit_meet_up/{id_meetup}
  defaults: { _controller: MeetUpBundle:MeetUp:edit}
  requirements:
    id: \d+        

lesrencontres:
  path: /lesrencontres
  defaults: { _controller: MeetUpBundle:MeetUp:lesrencontres}