meet_up_homepage:
    path:     /homepageMeetUp
    defaults: { _controller: MeetUpBundle:Default:index }

add_meet_up:
  path: /nouvelle_rencontre
  defaults: { _controller: MeetUpBundle:MeetUp:add}    

meet_up_view:
  path: /rencontre/{id}
  defaults: { _controller: MeetUpBundle:MeetUp:show}
  requirements:
    id: \d+

delete_meet_up:
  path: /supprimer_rencontre/{id}
  defaults: { _controller: MeetUpBundle:MeetUp:delete}
  requirements:
    id: \d+    

edit_meet_up:
  path: /modifier_rencontre/{id}
  defaults: { _controller: MeetUpBundle:MeetUp:edit}
  requirements:
    id: \d+        

add_commentaire_meet_up:
  path: /ajouter_commentaire/{id}
  defaults: { _controller: MeetUpBundle:CommentaireMeetUp:add_CommentaireMeetUp}    
  requirements:
    id: \d+  

delete_commentaire_meet_up:
  path: /supprimer_commentaire/{id}
  defaults: { _controller: MeetUpBundle:CommentaireMeetUp:delete_CommentaireMeetUp}    
  requirements:
    id: \d+  

add_vote_jour1:
  path: /ajout_vote_jour1/{id}
  defaults: { _controller: MeetUpBundle:MeetUp:increment_vote}
  requirements:
    id: \d+  

add_vote_jour2:
  path: /ajout_vote_jour2/{id}
  defaults: { _controller: MeetUpBundle:MeetUp:increment_vote}
  requirements:
    id: \d+  

add_vote_jour3:
  path: /ajout_vote_jour3/{id}
  defaults: { _controller: MeetUpBundle:MeetUp:increment_vote}    
  requirements:
    id: \d+  

lesrencontres: 
  path: /lesrencontres 
  defaults: { _controller:MeetUpBundle:MeetUp:lesrencontres}   
 
mesrencontres: 
  path: /mesrencontres 
  defaults: { _controller:MeetUpBundle:MeetUp:mesrencontres}   

ajout_participante:
  path: /ajout_participante/{id}
  defaults: { _controller:MeetUpBundle:MeetUp:ajoutparticipante}     
  requirements:
    id: \d+  

suppression_participante:
  path: /suppression_participante/{id}
  defaults: { _controller:MeetUpBundle:MeetUp:suppressionparticipante}     
  requirements:
    id: \d+    
    
recherche_departement_meetup: 
  path: /recherche_departement_meetup 
  defaults: { _controller:MeetUpBundle:SearchMeetup:search}    